# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.23
# 
# >> macros
# << macros

Name:       libical
Summary:    iCalendar library implementation in C (runtime)
Version:    0.48
Release:    1
Group:      System/Libraries
License:    LGPLv2.1 or MPLv1.0
URL:        http://sourceforge.net/projects/freeassociation/
Source0:    http://downloads.sourceforge.net/freeassociation/%{name}-%{version}.tar.gz
Source100:  libical.yaml
Patch0:     test_regression_fix.patch
Requires:   tzdata
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  tzdata


%description
libical is an open source implementation of the IETFs iCalendar calendaring
and scheduling protocols (RFC 2445, 2446, and 2447). It parses iCal 
components and provides a C API for manipulating the component properties, 
parameters, and subcomponents.

This package contains the files necessary for running applications that use
the libical library.



%package devel
Summary:    iCalendar library implementation in C (development)
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
libical is an open source implementation of the IETFs iCalendar 
calendaring and scheduling protocols (RFC 2445, 2446, and 2447). It 
parses iCal components and provides a C API for manipulating the 
component properties, parameters, and subcomponents.

This package contains the files necessary for developing applications
that use the libical library.



%prep
%setup -q -n %{name}-%{version}

# test_regression_fix.patch
%patch0 -p1
# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static
make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# Remove unpackaged files - static libraries
rm -f %{buildroot}%{_libdir}/libical*.a
# << install post



%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig





%files
%defattr(-,root,root,-)
# >> files
%doc LICENSE
%{_libdir}/libical.so.*
%{_libdir}/libicalss.so.*
%{_libdir}/libicalvcal.so.*
# << files


%files devel
%defattr(-,root,root,-)
# >> files devel
%doc NEWS
%doc README
%doc TODO
%{_includedir}/ical.h
%{_includedir}/libical/*.h
%{_libdir}/libical.so
%{_libdir}/libicalss.so
%{_libdir}/libicalvcal.so
%{_libdir}/pkgconfig/libical.pc
# << files devel

